// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user.proto

#include "user.pb.h"
#include "user.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace user {

static const char* UserService_method_names[] = {
  "/user.UserService/VerifyEmailCode",
  "/user.UserService/RegisterUser",
  "/user.UserService/VerifyLogin",
  "/user.UserService/ResetPassword",
  "/user.UserService/GetUserProfile",
  "/user.UserService/UpdateUserProfile",
};

std::unique_ptr< UserService::Stub> UserService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserService::Stub> stub(new UserService::Stub(channel, options));
  return stub;
}

UserService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_VerifyEmailCode_(UserService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterUser_(UserService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_VerifyLogin_(UserService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ResetPassword_(UserService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUserProfile_(UserService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateUserProfile_(UserService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserService::Stub::VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::user::VerifyEmailCodeResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::VerifyEmailCodeReq, ::user::VerifyEmailCodeResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VerifyEmailCode_, context, request, response);
}

void UserService::Stub::async::VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::VerifyEmailCodeReq, ::user::VerifyEmailCodeResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyEmailCode_, context, request, response, std::move(f));
}

void UserService::Stub::async::VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyEmailCode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::VerifyEmailCodeResp>* UserService::Stub::PrepareAsyncVerifyEmailCodeRaw(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::VerifyEmailCodeResp, ::user::VerifyEmailCodeReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VerifyEmailCode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::VerifyEmailCodeResp>* UserService::Stub::AsyncVerifyEmailCodeRaw(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVerifyEmailCodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::user::RegisterUserResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::RegisterUserReq, ::user::RegisterUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterUser_, context, request, response);
}

void UserService::Stub::async::RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::RegisterUserReq, ::user::RegisterUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterUser_, context, request, response, std::move(f));
}

void UserService::Stub::async::RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::RegisterUserResp>* UserService::Stub::PrepareAsyncRegisterUserRaw(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::RegisterUserResp, ::user::RegisterUserReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::RegisterUserResp>* UserService::Stub::AsyncRegisterUserRaw(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::user::VerifyLoginResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::VerifyLoginReq, ::user::VerifyLoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VerifyLogin_, context, request, response);
}

void UserService::Stub::async::VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::VerifyLoginReq, ::user::VerifyLoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyLogin_, context, request, response, std::move(f));
}

void UserService::Stub::async::VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyLogin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::VerifyLoginResp>* UserService::Stub::PrepareAsyncVerifyLoginRaw(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::VerifyLoginResp, ::user::VerifyLoginReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VerifyLogin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::VerifyLoginResp>* UserService::Stub::AsyncVerifyLoginRaw(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVerifyLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::user::ResetPasswordResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::ResetPasswordReq, ::user::ResetPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ResetPassword_, context, request, response);
}

void UserService::Stub::async::ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::ResetPasswordReq, ::user::ResetPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResetPassword_, context, request, response, std::move(f));
}

void UserService::Stub::async::ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResetPassword_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::ResetPasswordResp>* UserService::Stub::PrepareAsyncResetPasswordRaw(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::ResetPasswordResp, ::user::ResetPasswordReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ResetPassword_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::ResetPasswordResp>* UserService::Stub::AsyncResetPasswordRaw(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResetPasswordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::user::GetUserProfileResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::GetUserProfileReq, ::user::GetUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUserProfile_, context, request, response);
}

void UserService::Stub::async::GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::GetUserProfileReq, ::user::GetUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, std::move(f));
}

void UserService::Stub::async::GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::GetUserProfileResp>* UserService::Stub::PrepareAsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::GetUserProfileResp, ::user::GetUserProfileReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUserProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::GetUserProfileResp>* UserService::Stub::AsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUserProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::user::UpdateUserProfileResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::UpdateUserProfileReq, ::user::UpdateUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateUserProfile_, context, request, response);
}

void UserService::Stub::async::UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::UpdateUserProfileReq, ::user::UpdateUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUserProfile_, context, request, response, std::move(f));
}

void UserService::Stub::async::UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUserProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::UpdateUserProfileResp>* UserService::Stub::PrepareAsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::UpdateUserProfileResp, ::user::UpdateUserProfileReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateUserProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::UpdateUserProfileResp>* UserService::Stub::AsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateUserProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

UserService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::VerifyEmailCodeReq, ::user::VerifyEmailCodeResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::VerifyEmailCodeReq* req,
             ::user::VerifyEmailCodeResp* resp) {
               return service->VerifyEmailCode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::RegisterUserReq, ::user::RegisterUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::RegisterUserReq* req,
             ::user::RegisterUserResp* resp) {
               return service->RegisterUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::VerifyLoginReq, ::user::VerifyLoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::VerifyLoginReq* req,
             ::user::VerifyLoginResp* resp) {
               return service->VerifyLogin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::ResetPasswordReq, ::user::ResetPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::ResetPasswordReq* req,
             ::user::ResetPasswordResp* resp) {
               return service->ResetPassword(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::GetUserProfileReq, ::user::GetUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::GetUserProfileReq* req,
             ::user::GetUserProfileResp* resp) {
               return service->GetUserProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::UpdateUserProfileReq, ::user::UpdateUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::UpdateUserProfileReq* req,
             ::user::UpdateUserProfileResp* resp) {
               return service->UpdateUserProfile(ctx, req, resp);
             }, this)));
}

UserService::Service::~Service() {
}

::grpc::Status UserService::Service::VerifyEmailCode(::grpc::ServerContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::RegisterUser(::grpc::ServerContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::VerifyLogin(::grpc::ServerContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::ResetPassword(::grpc::ServerContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::GetUserProfile(::grpc::ServerContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::UpdateUserProfile(::grpc::ServerContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace user

