// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user.proto
#ifndef GRPC_user_2eproto__INCLUDED
#define GRPC_user_2eproto__INCLUDED

#include "user.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace user {

//
// ============= User Service =============
//  Handles:
//   - Registration
//   - Login verification
//   - Password reset
//   - Basic profile fetch
//   - CAPTCHA checking requested by GateServer
//
//
class UserService final {
 public:
  static constexpr char const* service_full_name() {
    return "user.UserService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 1. Verify email verification code
    virtual ::grpc::Status VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::user::VerifyEmailCodeResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyEmailCodeResp>> AsyncVerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyEmailCodeResp>>(AsyncVerifyEmailCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyEmailCodeResp>> PrepareAsyncVerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyEmailCodeResp>>(PrepareAsyncVerifyEmailCodeRaw(context, request, cq));
    }
    // 2. Register new user (idempotent)
    virtual ::grpc::Status RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::user::RegisterUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::RegisterUserResp>> AsyncRegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::RegisterUserResp>>(AsyncRegisterUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::RegisterUserResp>> PrepareAsyncRegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::RegisterUserResp>>(PrepareAsyncRegisterUserRaw(context, request, cq));
    }
    // 3. Login verification (password check)
    virtual ::grpc::Status VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::user::VerifyLoginResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyLoginResp>> AsyncVerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyLoginResp>>(AsyncVerifyLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyLoginResp>> PrepareAsyncVerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyLoginResp>>(PrepareAsyncVerifyLoginRaw(context, request, cq));
    }
    // 4. Reset password
    virtual ::grpc::Status ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::user::ResetPasswordResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::ResetPasswordResp>> AsyncResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::ResetPasswordResp>>(AsyncResetPasswordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::ResetPasswordResp>> PrepareAsyncResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::ResetPasswordResp>>(PrepareAsyncResetPasswordRaw(context, request, cq));
    }
    // 5. Fetch user basic info (for login or friend lists)
    virtual ::grpc::Status GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::user::GetUserProfileResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::GetUserProfileResp>> AsyncGetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::GetUserProfileResp>>(AsyncGetUserProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::GetUserProfileResp>> PrepareAsyncGetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::GetUserProfileResp>>(PrepareAsyncGetUserProfileRaw(context, request, cq));
    }
    // 6. Update user profile (not used yet by GateServer but necessary)
    virtual ::grpc::Status UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::user::UpdateUserProfileResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::UpdateUserProfileResp>> AsyncUpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::UpdateUserProfileResp>>(AsyncUpdateUserProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::UpdateUserProfileResp>> PrepareAsyncUpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::UpdateUserProfileResp>>(PrepareAsyncUpdateUserProfileRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 1. Verify email verification code
      virtual void VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 2. Register new user (idempotent)
      virtual void RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 3. Login verification (password check)
      virtual void VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 4. Reset password
      virtual void ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 5. Fetch user basic info (for login or friend lists)
      virtual void GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 6. Update user profile (not used yet by GateServer but necessary)
      virtual void UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyEmailCodeResp>* AsyncVerifyEmailCodeRaw(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyEmailCodeResp>* PrepareAsyncVerifyEmailCodeRaw(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::RegisterUserResp>* AsyncRegisterUserRaw(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::RegisterUserResp>* PrepareAsyncRegisterUserRaw(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyLoginResp>* AsyncVerifyLoginRaw(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::VerifyLoginResp>* PrepareAsyncVerifyLoginRaw(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::ResetPasswordResp>* AsyncResetPasswordRaw(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::ResetPasswordResp>* PrepareAsyncResetPasswordRaw(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::GetUserProfileResp>* AsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::GetUserProfileResp>* PrepareAsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::UpdateUserProfileResp>* AsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::UpdateUserProfileResp>* PrepareAsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::user::VerifyEmailCodeResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::VerifyEmailCodeResp>> AsyncVerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::VerifyEmailCodeResp>>(AsyncVerifyEmailCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::VerifyEmailCodeResp>> PrepareAsyncVerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::VerifyEmailCodeResp>>(PrepareAsyncVerifyEmailCodeRaw(context, request, cq));
    }
    ::grpc::Status RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::user::RegisterUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::RegisterUserResp>> AsyncRegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::RegisterUserResp>>(AsyncRegisterUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::RegisterUserResp>> PrepareAsyncRegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::RegisterUserResp>>(PrepareAsyncRegisterUserRaw(context, request, cq));
    }
    ::grpc::Status VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::user::VerifyLoginResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::VerifyLoginResp>> AsyncVerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::VerifyLoginResp>>(AsyncVerifyLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::VerifyLoginResp>> PrepareAsyncVerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::VerifyLoginResp>>(PrepareAsyncVerifyLoginRaw(context, request, cq));
    }
    ::grpc::Status ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::user::ResetPasswordResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::ResetPasswordResp>> AsyncResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::ResetPasswordResp>>(AsyncResetPasswordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::ResetPasswordResp>> PrepareAsyncResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::ResetPasswordResp>>(PrepareAsyncResetPasswordRaw(context, request, cq));
    }
    ::grpc::Status GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::user::GetUserProfileResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::GetUserProfileResp>> AsyncGetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::GetUserProfileResp>>(AsyncGetUserProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::GetUserProfileResp>> PrepareAsyncGetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::GetUserProfileResp>>(PrepareAsyncGetUserProfileRaw(context, request, cq));
    }
    ::grpc::Status UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::user::UpdateUserProfileResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::UpdateUserProfileResp>> AsyncUpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::UpdateUserProfileResp>>(AsyncUpdateUserProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::UpdateUserProfileResp>> PrepareAsyncUpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::UpdateUserProfileResp>>(PrepareAsyncUpdateUserProfileRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response, std::function<void(::grpc::Status)>) override;
      void VerifyEmailCode(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response, std::function<void(::grpc::Status)>) override;
      void RegisterUser(::grpc::ClientContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response, std::function<void(::grpc::Status)>) override;
      void VerifyLogin(::grpc::ClientContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response, std::function<void(::grpc::Status)>) override;
      void ResetPassword(::grpc::ClientContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response, std::function<void(::grpc::Status)>) override;
      void GetUserProfile(::grpc::ClientContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response, std::function<void(::grpc::Status)>) override;
      void UpdateUserProfile(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::user::VerifyEmailCodeResp>* AsyncVerifyEmailCodeRaw(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::VerifyEmailCodeResp>* PrepareAsyncVerifyEmailCodeRaw(::grpc::ClientContext* context, const ::user::VerifyEmailCodeReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::RegisterUserResp>* AsyncRegisterUserRaw(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::RegisterUserResp>* PrepareAsyncRegisterUserRaw(::grpc::ClientContext* context, const ::user::RegisterUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::VerifyLoginResp>* AsyncVerifyLoginRaw(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::VerifyLoginResp>* PrepareAsyncVerifyLoginRaw(::grpc::ClientContext* context, const ::user::VerifyLoginReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::ResetPasswordResp>* AsyncResetPasswordRaw(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::ResetPasswordResp>* PrepareAsyncResetPasswordRaw(::grpc::ClientContext* context, const ::user::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::GetUserProfileResp>* AsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::GetUserProfileResp>* PrepareAsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::user::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::UpdateUserProfileResp>* AsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::UpdateUserProfileResp>* PrepareAsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::user::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_VerifyEmailCode_;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterUser_;
    const ::grpc::internal::RpcMethod rpcmethod_VerifyLogin_;
    const ::grpc::internal::RpcMethod rpcmethod_ResetPassword_;
    const ::grpc::internal::RpcMethod rpcmethod_GetUserProfile_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateUserProfile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 1. Verify email verification code
    virtual ::grpc::Status VerifyEmailCode(::grpc::ServerContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response);
    // 2. Register new user (idempotent)
    virtual ::grpc::Status RegisterUser(::grpc::ServerContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response);
    // 3. Login verification (password check)
    virtual ::grpc::Status VerifyLogin(::grpc::ServerContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response);
    // 4. Reset password
    virtual ::grpc::Status ResetPassword(::grpc::ServerContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response);
    // 5. Fetch user basic info (for login or friend lists)
    virtual ::grpc::Status GetUserProfile(::grpc::ServerContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response);
    // 6. Update user profile (not used yet by GateServer but necessary)
    virtual ::grpc::Status UpdateUserProfile(::grpc::ServerContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifyEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VerifyEmailCode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_VerifyEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyEmailCode(::grpc::ServerContext* /*context*/, const ::user::VerifyEmailCodeReq* /*request*/, ::user::VerifyEmailCodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyEmailCode(::grpc::ServerContext* context, ::user::VerifyEmailCodeReq* request, ::grpc::ServerAsyncResponseWriter< ::user::VerifyEmailCodeResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterUser() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::user::RegisterUserReq* /*request*/, ::user::RegisterUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterUser(::grpc::ServerContext* context, ::user::RegisterUserReq* request, ::grpc::ServerAsyncResponseWriter< ::user::RegisterUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifyLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VerifyLogin() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_VerifyLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyLogin(::grpc::ServerContext* /*context*/, const ::user::VerifyLoginReq* /*request*/, ::user::VerifyLoginResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyLogin(::grpc::ServerContext* context, ::user::VerifyLoginReq* request, ::grpc::ServerAsyncResponseWriter< ::user::VerifyLoginResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ResetPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ResetPassword() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ResetPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetPassword(::grpc::ServerContext* /*context*/, const ::user::ResetPasswordReq* /*request*/, ::user::ResetPasswordResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResetPassword(::grpc::ServerContext* context, ::user::ResetPasswordReq* request, ::grpc::ServerAsyncResponseWriter< ::user::ResetPasswordResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUserProfile() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_GetUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProfile(::grpc::ServerContext* /*context*/, const ::user::GetUserProfileReq* /*request*/, ::user::GetUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserProfile(::grpc::ServerContext* context, ::user::GetUserProfileReq* request, ::grpc::ServerAsyncResponseWriter< ::user::GetUserProfileResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateUserProfile() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_UpdateUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserProfile(::grpc::ServerContext* /*context*/, const ::user::UpdateUserProfileReq* /*request*/, ::user::UpdateUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateUserProfile(::grpc::ServerContext* context, ::user::UpdateUserProfileReq* request, ::grpc::ServerAsyncResponseWriter< ::user::UpdateUserProfileResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_VerifyEmailCode<WithAsyncMethod_RegisterUser<WithAsyncMethod_VerifyLogin<WithAsyncMethod_ResetPassword<WithAsyncMethod_GetUserProfile<WithAsyncMethod_UpdateUserProfile<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_VerifyEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VerifyEmailCode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::user::VerifyEmailCodeReq, ::user::VerifyEmailCodeResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::VerifyEmailCodeReq* request, ::user::VerifyEmailCodeResp* response) { return this->VerifyEmailCode(context, request, response); }));}
    void SetMessageAllocatorFor_VerifyEmailCode(
        ::grpc::MessageAllocator< ::user::VerifyEmailCodeReq, ::user::VerifyEmailCodeResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::VerifyEmailCodeReq, ::user::VerifyEmailCodeResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VerifyEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyEmailCode(::grpc::ServerContext* /*context*/, const ::user::VerifyEmailCodeReq* /*request*/, ::user::VerifyEmailCodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyEmailCode(
      ::grpc::CallbackServerContext* /*context*/, const ::user::VerifyEmailCodeReq* /*request*/, ::user::VerifyEmailCodeResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterUser() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::user::RegisterUserReq, ::user::RegisterUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::RegisterUserReq* request, ::user::RegisterUserResp* response) { return this->RegisterUser(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterUser(
        ::grpc::MessageAllocator< ::user::RegisterUserReq, ::user::RegisterUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::RegisterUserReq, ::user::RegisterUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::user::RegisterUserReq* /*request*/, ::user::RegisterUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterUser(
      ::grpc::CallbackServerContext* /*context*/, const ::user::RegisterUserReq* /*request*/, ::user::RegisterUserResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_VerifyLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VerifyLogin() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::user::VerifyLoginReq, ::user::VerifyLoginResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::VerifyLoginReq* request, ::user::VerifyLoginResp* response) { return this->VerifyLogin(context, request, response); }));}
    void SetMessageAllocatorFor_VerifyLogin(
        ::grpc::MessageAllocator< ::user::VerifyLoginReq, ::user::VerifyLoginResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::VerifyLoginReq, ::user::VerifyLoginResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VerifyLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyLogin(::grpc::ServerContext* /*context*/, const ::user::VerifyLoginReq* /*request*/, ::user::VerifyLoginResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyLogin(
      ::grpc::CallbackServerContext* /*context*/, const ::user::VerifyLoginReq* /*request*/, ::user::VerifyLoginResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ResetPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ResetPassword() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::user::ResetPasswordReq, ::user::ResetPasswordResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::ResetPasswordReq* request, ::user::ResetPasswordResp* response) { return this->ResetPassword(context, request, response); }));}
    void SetMessageAllocatorFor_ResetPassword(
        ::grpc::MessageAllocator< ::user::ResetPasswordReq, ::user::ResetPasswordResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::ResetPasswordReq, ::user::ResetPasswordResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ResetPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetPassword(::grpc::ServerContext* /*context*/, const ::user::ResetPasswordReq* /*request*/, ::user::ResetPasswordResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ResetPassword(
      ::grpc::CallbackServerContext* /*context*/, const ::user::ResetPasswordReq* /*request*/, ::user::ResetPasswordResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUserProfile() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::user::GetUserProfileReq, ::user::GetUserProfileResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::GetUserProfileReq* request, ::user::GetUserProfileResp* response) { return this->GetUserProfile(context, request, response); }));}
    void SetMessageAllocatorFor_GetUserProfile(
        ::grpc::MessageAllocator< ::user::GetUserProfileReq, ::user::GetUserProfileResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::GetUserProfileReq, ::user::GetUserProfileResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProfile(::grpc::ServerContext* /*context*/, const ::user::GetUserProfileReq* /*request*/, ::user::GetUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::user::GetUserProfileReq* /*request*/, ::user::GetUserProfileResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateUserProfile() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::user::UpdateUserProfileReq, ::user::UpdateUserProfileResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::UpdateUserProfileReq* request, ::user::UpdateUserProfileResp* response) { return this->UpdateUserProfile(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateUserProfile(
        ::grpc::MessageAllocator< ::user::UpdateUserProfileReq, ::user::UpdateUserProfileResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::UpdateUserProfileReq, ::user::UpdateUserProfileResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserProfile(::grpc::ServerContext* /*context*/, const ::user::UpdateUserProfileReq* /*request*/, ::user::UpdateUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateUserProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::user::UpdateUserProfileReq* /*request*/, ::user::UpdateUserProfileResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_VerifyEmailCode<WithCallbackMethod_RegisterUser<WithCallbackMethod_VerifyLogin<WithCallbackMethod_ResetPassword<WithCallbackMethod_GetUserProfile<WithCallbackMethod_UpdateUserProfile<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_VerifyEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VerifyEmailCode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_VerifyEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyEmailCode(::grpc::ServerContext* /*context*/, const ::user::VerifyEmailCodeReq* /*request*/, ::user::VerifyEmailCodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterUser() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::user::RegisterUserReq* /*request*/, ::user::RegisterUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VerifyLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VerifyLogin() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_VerifyLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyLogin(::grpc::ServerContext* /*context*/, const ::user::VerifyLoginReq* /*request*/, ::user::VerifyLoginResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ResetPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ResetPassword() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ResetPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetPassword(::grpc::ServerContext* /*context*/, const ::user::ResetPasswordReq* /*request*/, ::user::ResetPasswordResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUserProfile() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_GetUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProfile(::grpc::ServerContext* /*context*/, const ::user::GetUserProfileReq* /*request*/, ::user::GetUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateUserProfile() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_UpdateUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserProfile(::grpc::ServerContext* /*context*/, const ::user::UpdateUserProfileReq* /*request*/, ::user::UpdateUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifyEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VerifyEmailCode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_VerifyEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyEmailCode(::grpc::ServerContext* /*context*/, const ::user::VerifyEmailCodeReq* /*request*/, ::user::VerifyEmailCodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyEmailCode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterUser() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::user::RegisterUserReq* /*request*/, ::user::RegisterUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifyLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VerifyLogin() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_VerifyLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyLogin(::grpc::ServerContext* /*context*/, const ::user::VerifyLoginReq* /*request*/, ::user::VerifyLoginResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyLogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ResetPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ResetPassword() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ResetPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetPassword(::grpc::ServerContext* /*context*/, const ::user::ResetPasswordReq* /*request*/, ::user::ResetPasswordResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResetPassword(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUserProfile() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_GetUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProfile(::grpc::ServerContext* /*context*/, const ::user::GetUserProfileReq* /*request*/, ::user::GetUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserProfile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateUserProfile() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_UpdateUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserProfile(::grpc::ServerContext* /*context*/, const ::user::UpdateUserProfileReq* /*request*/, ::user::UpdateUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateUserProfile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VerifyEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VerifyEmailCode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VerifyEmailCode(context, request, response); }));
    }
    ~WithRawCallbackMethod_VerifyEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyEmailCode(::grpc::ServerContext* /*context*/, const ::user::VerifyEmailCodeReq* /*request*/, ::user::VerifyEmailCodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyEmailCode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterUser() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::user::RegisterUserReq* /*request*/, ::user::RegisterUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VerifyLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VerifyLogin() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VerifyLogin(context, request, response); }));
    }
    ~WithRawCallbackMethod_VerifyLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyLogin(::grpc::ServerContext* /*context*/, const ::user::VerifyLoginReq* /*request*/, ::user::VerifyLoginResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyLogin(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ResetPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ResetPassword() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ResetPassword(context, request, response); }));
    }
    ~WithRawCallbackMethod_ResetPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetPassword(::grpc::ServerContext* /*context*/, const ::user::ResetPasswordReq* /*request*/, ::user::ResetPasswordResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ResetPassword(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUserProfile() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUserProfile(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProfile(::grpc::ServerContext* /*context*/, const ::user::GetUserProfileReq* /*request*/, ::user::GetUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateUserProfile() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateUserProfile(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserProfile(::grpc::ServerContext* /*context*/, const ::user::UpdateUserProfileReq* /*request*/, ::user::UpdateUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateUserProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifyEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VerifyEmailCode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::VerifyEmailCodeReq, ::user::VerifyEmailCodeResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::VerifyEmailCodeReq, ::user::VerifyEmailCodeResp>* streamer) {
                       return this->StreamedVerifyEmailCode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VerifyEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifyEmailCode(::grpc::ServerContext* /*context*/, const ::user::VerifyEmailCodeReq* /*request*/, ::user::VerifyEmailCodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifyEmailCode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::VerifyEmailCodeReq,::user::VerifyEmailCodeResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterUser() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::RegisterUserReq, ::user::RegisterUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::RegisterUserReq, ::user::RegisterUserResp>* streamer) {
                       return this->StreamedRegisterUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::user::RegisterUserReq* /*request*/, ::user::RegisterUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::RegisterUserReq,::user::RegisterUserResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifyLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VerifyLogin() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::VerifyLoginReq, ::user::VerifyLoginResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::VerifyLoginReq, ::user::VerifyLoginResp>* streamer) {
                       return this->StreamedVerifyLogin(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VerifyLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifyLogin(::grpc::ServerContext* /*context*/, const ::user::VerifyLoginReq* /*request*/, ::user::VerifyLoginResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifyLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::VerifyLoginReq,::user::VerifyLoginResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ResetPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ResetPassword() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::ResetPasswordReq, ::user::ResetPasswordResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::ResetPasswordReq, ::user::ResetPasswordResp>* streamer) {
                       return this->StreamedResetPassword(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ResetPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ResetPassword(::grpc::ServerContext* /*context*/, const ::user::ResetPasswordReq* /*request*/, ::user::ResetPasswordResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedResetPassword(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::ResetPasswordReq,::user::ResetPasswordResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUserProfile() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::GetUserProfileReq, ::user::GetUserProfileResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::GetUserProfileReq, ::user::GetUserProfileResp>* streamer) {
                       return this->StreamedGetUserProfile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUserProfile(::grpc::ServerContext* /*context*/, const ::user::GetUserProfileReq* /*request*/, ::user::GetUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUserProfile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::GetUserProfileReq,::user::GetUserProfileResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateUserProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateUserProfile() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::UpdateUserProfileReq, ::user::UpdateUserProfileResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::UpdateUserProfileReq, ::user::UpdateUserProfileResp>* streamer) {
                       return this->StreamedUpdateUserProfile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateUserProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateUserProfile(::grpc::ServerContext* /*context*/, const ::user::UpdateUserProfileReq* /*request*/, ::user::UpdateUserProfileResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateUserProfile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::UpdateUserProfileReq,::user::UpdateUserProfileResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_VerifyEmailCode<WithStreamedUnaryMethod_RegisterUser<WithStreamedUnaryMethod_VerifyLogin<WithStreamedUnaryMethod_ResetPassword<WithStreamedUnaryMethod_GetUserProfile<WithStreamedUnaryMethod_UpdateUserProfile<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_VerifyEmailCode<WithStreamedUnaryMethod_RegisterUser<WithStreamedUnaryMethod_VerifyLogin<WithStreamedUnaryMethod_ResetPassword<WithStreamedUnaryMethod_GetUserProfile<WithStreamedUnaryMethod_UpdateUserProfile<Service > > > > > > StreamedService;
};

}  // namespace user


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_user_2eproto__INCLUDED
