// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat.proto
#ifndef GRPC_chat_2eproto__INCLUDED
#define GRPC_chat_2eproto__INCLUDED

#include "chat.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace chat {

class ChatService final {
 public:
  static constexpr char const* service_full_name() {
    return "chat.ChatService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // kick user if already online
    virtual ::grpc::Status KickUser(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::chat::KickUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::KickUserResp>> AsyncKickUser(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::KickUserResp>>(AsyncKickUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::KickUserResp>> PrepareAsyncKickUser(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::KickUserResp>>(PrepareAsyncKickUserRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // kick user if already online
      virtual void KickUser(::grpc::ClientContext* context, const ::chat::KickUserReq* request, ::chat::KickUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void KickUser(::grpc::ClientContext* context, const ::chat::KickUserReq* request, ::chat::KickUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::KickUserResp>* AsyncKickUserRaw(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::KickUserResp>* PrepareAsyncKickUserRaw(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status KickUser(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::chat::KickUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::KickUserResp>> AsyncKickUser(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::KickUserResp>>(AsyncKickUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::KickUserResp>> PrepareAsyncKickUser(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::KickUserResp>>(PrepareAsyncKickUserRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void KickUser(::grpc::ClientContext* context, const ::chat::KickUserReq* request, ::chat::KickUserResp* response, std::function<void(::grpc::Status)>) override;
      void KickUser(::grpc::ClientContext* context, const ::chat::KickUserReq* request, ::chat::KickUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::chat::KickUserResp>* AsyncKickUserRaw(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::KickUserResp>* PrepareAsyncKickUserRaw(::grpc::ClientContext* context, const ::chat::KickUserReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_KickUser_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // kick user if already online
    virtual ::grpc::Status KickUser(::grpc::ServerContext* context, const ::chat::KickUserReq* request, ::chat::KickUserResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_KickUser() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::chat::KickUserReq* /*request*/, ::chat::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestKickUser(::grpc::ServerContext* context, ::chat::KickUserReq* request, ::grpc::ServerAsyncResponseWriter< ::chat::KickUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_KickUser<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_KickUser() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::KickUserReq, ::chat::KickUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::KickUserReq* request, ::chat::KickUserResp* response) { return this->KickUser(context, request, response); }));}
    void SetMessageAllocatorFor_KickUser(
        ::grpc::MessageAllocator< ::chat::KickUserReq, ::chat::KickUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::KickUserReq, ::chat::KickUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::chat::KickUserReq* /*request*/, ::chat::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* KickUser(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::KickUserReq* /*request*/, ::chat::KickUserResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_KickUser<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_KickUser() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::chat::KickUserReq* /*request*/, ::chat::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_KickUser() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::chat::KickUserReq* /*request*/, ::chat::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestKickUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_KickUser() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->KickUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::chat::KickUserReq* /*request*/, ::chat::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* KickUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_KickUser() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::KickUserReq, ::chat::KickUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::KickUserReq, ::chat::KickUserResp>* streamer) {
                       return this->StreamedKickUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::chat::KickUserReq* /*request*/, ::chat::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedKickUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::KickUserReq,::chat::KickUserResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_KickUser<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_KickUser<Service > StreamedService;
};

}  // namespace chat


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_chat_2eproto__INCLUDED
