// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: status.proto
#ifndef GRPC_status_2eproto__INCLUDED
#define GRPC_status_2eproto__INCLUDED

#include "status.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace status {

class StatusService final {
 public:
  static constexpr char const* service_full_name() {
    return "status.StatusService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Node lifecycle
    virtual ::grpc::Status RegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::status::RegisterNodeResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::RegisterNodeResp>> AsyncRegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::RegisterNodeResp>>(AsyncRegisterNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::RegisterNodeResp>> PrepareAsyncRegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::RegisterNodeResp>>(PrepareAsyncRegisterNodeRaw(context, request, cq));
    }
    virtual ::grpc::Status DeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::status::DeregisterNodeResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::DeregisterNodeResp>> AsyncDeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::DeregisterNodeResp>>(AsyncDeregisterNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::DeregisterNodeResp>> PrepareAsyncDeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::DeregisterNodeResp>>(PrepareAsyncDeregisterNodeRaw(context, request, cq));
    }
    virtual ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::status::HeartbeatResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::HeartbeatResp>> AsyncHeartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::HeartbeatResp>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::HeartbeatResp>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::HeartbeatResp>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    // load balancing / allocation
    virtual ::grpc::Status AllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::status::AllocateServerResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::AllocateServerResp>> AsyncAllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::AllocateServerResp>>(AsyncAllocateServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::AllocateServerResp>> PrepareAsyncAllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::AllocateServerResp>>(PrepareAsyncAllocateServerRaw(context, request, cq));
    }
    // user presence / routing
    virtual ::grpc::Status ReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::status::OnlineReportResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::OnlineReportResp>> AsyncReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::OnlineReportResp>>(AsyncReportOnlineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::OnlineReportResp>> PrepareAsyncReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::OnlineReportResp>>(PrepareAsyncReportOnlineRaw(context, request, cq));
    }
    virtual ::grpc::Status ReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::status::OfflineReportResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::OfflineReportResp>> AsyncReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::OfflineReportResp>>(AsyncReportOfflineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::OfflineReportResp>> PrepareAsyncReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::OfflineReportResp>>(PrepareAsyncReportOfflineRaw(context, request, cq));
    }
    virtual ::grpc::Status QueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq& request, ::status::RouteResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::RouteResp>> AsyncQueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::RouteResp>>(AsyncQueryUserRouteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::RouteResp>> PrepareAsyncQueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::RouteResp>>(PrepareAsyncQueryUserRouteRaw(context, request, cq));
    }
    // kick user if already online
    virtual ::grpc::Status KickUser(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::status::KickUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::KickUserResp>> AsyncKickUser(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::KickUserResp>>(AsyncKickUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::KickUserResp>> PrepareAsyncKickUser(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::KickUserResp>>(PrepareAsyncKickUserRaw(context, request, cq));
    }
    // admin
    virtual ::grpc::Status GetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::status::GetNodesResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::GetNodesResp>> AsyncGetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::GetNodesResp>>(AsyncGetNodesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::GetNodesResp>> PrepareAsyncGetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::status::GetNodesResp>>(PrepareAsyncGetNodesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Node lifecycle
      virtual void RegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq* request, ::status::RegisterNodeResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq* request, ::status::RegisterNodeResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq* request, ::status::DeregisterNodeResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq* request, ::status::DeregisterNodeResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq* request, ::status::HeartbeatResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq* request, ::status::HeartbeatResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // load balancing / allocation
      virtual void AllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq* request, ::status::AllocateServerResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq* request, ::status::AllocateServerResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // user presence / routing
      virtual void ReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq* request, ::status::OnlineReportResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq* request, ::status::OnlineReportResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq* request, ::status::OfflineReportResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq* request, ::status::OfflineReportResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void QueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq* request, ::status::RouteResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void QueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq* request, ::status::RouteResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // kick user if already online
      virtual void KickUser(::grpc::ClientContext* context, const ::status::KickUserReq* request, ::status::KickUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void KickUser(::grpc::ClientContext* context, const ::status::KickUserReq* request, ::status::KickUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // admin
      virtual void GetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq* request, ::status::GetNodesResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq* request, ::status::GetNodesResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::RegisterNodeResp>* AsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::RegisterNodeResp>* PrepareAsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::DeregisterNodeResp>* AsyncDeregisterNodeRaw(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::DeregisterNodeResp>* PrepareAsyncDeregisterNodeRaw(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::HeartbeatResp>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::HeartbeatResp>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::AllocateServerResp>* AsyncAllocateServerRaw(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::AllocateServerResp>* PrepareAsyncAllocateServerRaw(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::OnlineReportResp>* AsyncReportOnlineRaw(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::OnlineReportResp>* PrepareAsyncReportOnlineRaw(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::OfflineReportResp>* AsyncReportOfflineRaw(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::OfflineReportResp>* PrepareAsyncReportOfflineRaw(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::RouteResp>* AsyncQueryUserRouteRaw(::grpc::ClientContext* context, const ::status::RouteReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::RouteResp>* PrepareAsyncQueryUserRouteRaw(::grpc::ClientContext* context, const ::status::RouteReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::KickUserResp>* AsyncKickUserRaw(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::KickUserResp>* PrepareAsyncKickUserRaw(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::GetNodesResp>* AsyncGetNodesRaw(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::status::GetNodesResp>* PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::status::RegisterNodeResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::RegisterNodeResp>> AsyncRegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::RegisterNodeResp>>(AsyncRegisterNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::RegisterNodeResp>> PrepareAsyncRegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::RegisterNodeResp>>(PrepareAsyncRegisterNodeRaw(context, request, cq));
    }
    ::grpc::Status DeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::status::DeregisterNodeResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::DeregisterNodeResp>> AsyncDeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::DeregisterNodeResp>>(AsyncDeregisterNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::DeregisterNodeResp>> PrepareAsyncDeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::DeregisterNodeResp>>(PrepareAsyncDeregisterNodeRaw(context, request, cq));
    }
    ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::status::HeartbeatResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::HeartbeatResp>> AsyncHeartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::HeartbeatResp>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::HeartbeatResp>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::HeartbeatResp>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    ::grpc::Status AllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::status::AllocateServerResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::AllocateServerResp>> AsyncAllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::AllocateServerResp>>(AsyncAllocateServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::AllocateServerResp>> PrepareAsyncAllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::AllocateServerResp>>(PrepareAsyncAllocateServerRaw(context, request, cq));
    }
    ::grpc::Status ReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::status::OnlineReportResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::OnlineReportResp>> AsyncReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::OnlineReportResp>>(AsyncReportOnlineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::OnlineReportResp>> PrepareAsyncReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::OnlineReportResp>>(PrepareAsyncReportOnlineRaw(context, request, cq));
    }
    ::grpc::Status ReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::status::OfflineReportResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::OfflineReportResp>> AsyncReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::OfflineReportResp>>(AsyncReportOfflineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::OfflineReportResp>> PrepareAsyncReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::OfflineReportResp>>(PrepareAsyncReportOfflineRaw(context, request, cq));
    }
    ::grpc::Status QueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq& request, ::status::RouteResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::RouteResp>> AsyncQueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::RouteResp>>(AsyncQueryUserRouteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::RouteResp>> PrepareAsyncQueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::RouteResp>>(PrepareAsyncQueryUserRouteRaw(context, request, cq));
    }
    ::grpc::Status KickUser(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::status::KickUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::KickUserResp>> AsyncKickUser(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::KickUserResp>>(AsyncKickUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::KickUserResp>> PrepareAsyncKickUser(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::KickUserResp>>(PrepareAsyncKickUserRaw(context, request, cq));
    }
    ::grpc::Status GetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::status::GetNodesResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::GetNodesResp>> AsyncGetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::GetNodesResp>>(AsyncGetNodesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::GetNodesResp>> PrepareAsyncGetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::status::GetNodesResp>>(PrepareAsyncGetNodesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq* request, ::status::RegisterNodeResp* response, std::function<void(::grpc::Status)>) override;
      void RegisterNode(::grpc::ClientContext* context, const ::status::RegisterNodeReq* request, ::status::RegisterNodeResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq* request, ::status::DeregisterNodeResp* response, std::function<void(::grpc::Status)>) override;
      void DeregisterNode(::grpc::ClientContext* context, const ::status::DeregisterNodeReq* request, ::status::DeregisterNodeResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Heartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq* request, ::status::HeartbeatResp* response, std::function<void(::grpc::Status)>) override;
      void Heartbeat(::grpc::ClientContext* context, const ::status::HeartbeatReq* request, ::status::HeartbeatResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq* request, ::status::AllocateServerResp* response, std::function<void(::grpc::Status)>) override;
      void AllocateServer(::grpc::ClientContext* context, const ::status::AllocateServerReq* request, ::status::AllocateServerResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq* request, ::status::OnlineReportResp* response, std::function<void(::grpc::Status)>) override;
      void ReportOnline(::grpc::ClientContext* context, const ::status::OnlineReportReq* request, ::status::OnlineReportResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq* request, ::status::OfflineReportResp* response, std::function<void(::grpc::Status)>) override;
      void ReportOffline(::grpc::ClientContext* context, const ::status::OfflineReportReq* request, ::status::OfflineReportResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void QueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq* request, ::status::RouteResp* response, std::function<void(::grpc::Status)>) override;
      void QueryUserRoute(::grpc::ClientContext* context, const ::status::RouteReq* request, ::status::RouteResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void KickUser(::grpc::ClientContext* context, const ::status::KickUserReq* request, ::status::KickUserResp* response, std::function<void(::grpc::Status)>) override;
      void KickUser(::grpc::ClientContext* context, const ::status::KickUserReq* request, ::status::KickUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq* request, ::status::GetNodesResp* response, std::function<void(::grpc::Status)>) override;
      void GetNodes(::grpc::ClientContext* context, const ::status::GetNodesReq* request, ::status::GetNodesResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::status::RegisterNodeResp>* AsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::RegisterNodeResp>* PrepareAsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::status::RegisterNodeReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::DeregisterNodeResp>* AsyncDeregisterNodeRaw(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::DeregisterNodeResp>* PrepareAsyncDeregisterNodeRaw(::grpc::ClientContext* context, const ::status::DeregisterNodeReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::HeartbeatResp>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::HeartbeatResp>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::status::HeartbeatReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::AllocateServerResp>* AsyncAllocateServerRaw(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::AllocateServerResp>* PrepareAsyncAllocateServerRaw(::grpc::ClientContext* context, const ::status::AllocateServerReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::OnlineReportResp>* AsyncReportOnlineRaw(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::OnlineReportResp>* PrepareAsyncReportOnlineRaw(::grpc::ClientContext* context, const ::status::OnlineReportReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::OfflineReportResp>* AsyncReportOfflineRaw(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::OfflineReportResp>* PrepareAsyncReportOfflineRaw(::grpc::ClientContext* context, const ::status::OfflineReportReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::RouteResp>* AsyncQueryUserRouteRaw(::grpc::ClientContext* context, const ::status::RouteReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::RouteResp>* PrepareAsyncQueryUserRouteRaw(::grpc::ClientContext* context, const ::status::RouteReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::KickUserResp>* AsyncKickUserRaw(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::KickUserResp>* PrepareAsyncKickUserRaw(::grpc::ClientContext* context, const ::status::KickUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::GetNodesResp>* AsyncGetNodesRaw(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::status::GetNodesResp>* PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::status::GetNodesReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterNode_;
    const ::grpc::internal::RpcMethod rpcmethod_DeregisterNode_;
    const ::grpc::internal::RpcMethod rpcmethod_Heartbeat_;
    const ::grpc::internal::RpcMethod rpcmethod_AllocateServer_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportOnline_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportOffline_;
    const ::grpc::internal::RpcMethod rpcmethod_QueryUserRoute_;
    const ::grpc::internal::RpcMethod rpcmethod_KickUser_;
    const ::grpc::internal::RpcMethod rpcmethod_GetNodes_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Node lifecycle
    virtual ::grpc::Status RegisterNode(::grpc::ServerContext* context, const ::status::RegisterNodeReq* request, ::status::RegisterNodeResp* response);
    virtual ::grpc::Status DeregisterNode(::grpc::ServerContext* context, const ::status::DeregisterNodeReq* request, ::status::DeregisterNodeResp* response);
    virtual ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::status::HeartbeatReq* request, ::status::HeartbeatResp* response);
    // load balancing / allocation
    virtual ::grpc::Status AllocateServer(::grpc::ServerContext* context, const ::status::AllocateServerReq* request, ::status::AllocateServerResp* response);
    // user presence / routing
    virtual ::grpc::Status ReportOnline(::grpc::ServerContext* context, const ::status::OnlineReportReq* request, ::status::OnlineReportResp* response);
    virtual ::grpc::Status ReportOffline(::grpc::ServerContext* context, const ::status::OfflineReportReq* request, ::status::OfflineReportResp* response);
    virtual ::grpc::Status QueryUserRoute(::grpc::ServerContext* context, const ::status::RouteReq* request, ::status::RouteResp* response);
    // kick user if already online
    virtual ::grpc::Status KickUser(::grpc::ServerContext* context, const ::status::KickUserReq* request, ::status::KickUserResp* response);
    // admin
    virtual ::grpc::Status GetNodes(::grpc::ServerContext* context, const ::status::GetNodesReq* request, ::status::GetNodesResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterNode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::status::RegisterNodeReq* /*request*/, ::status::RegisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterNode(::grpc::ServerContext* context, ::status::RegisterNodeReq* request, ::grpc::ServerAsyncResponseWriter< ::status::RegisterNodeResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeregisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeregisterNode() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DeregisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeregisterNode(::grpc::ServerContext* /*context*/, const ::status::DeregisterNodeReq* /*request*/, ::status::DeregisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeregisterNode(::grpc::ServerContext* context, ::status::DeregisterNodeReq* request, ::grpc::ServerAsyncResponseWriter< ::status::DeregisterNodeResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Heartbeat() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::status::HeartbeatReq* /*request*/, ::status::HeartbeatResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::status::HeartbeatReq* request, ::grpc::ServerAsyncResponseWriter< ::status::HeartbeatResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AllocateServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AllocateServer() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_AllocateServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateServer(::grpc::ServerContext* /*context*/, const ::status::AllocateServerReq* /*request*/, ::status::AllocateServerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAllocateServer(::grpc::ServerContext* context, ::status::AllocateServerReq* request, ::grpc::ServerAsyncResponseWriter< ::status::AllocateServerResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportOnline() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_ReportOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOnline(::grpc::ServerContext* /*context*/, const ::status::OnlineReportReq* /*request*/, ::status::OnlineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportOnline(::grpc::ServerContext* context, ::status::OnlineReportReq* request, ::grpc::ServerAsyncResponseWriter< ::status::OnlineReportResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportOffline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportOffline() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_ReportOffline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOffline(::grpc::ServerContext* /*context*/, const ::status::OfflineReportReq* /*request*/, ::status::OfflineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportOffline(::grpc::ServerContext* context, ::status::OfflineReportReq* request, ::grpc::ServerAsyncResponseWriter< ::status::OfflineReportResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryUserRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_QueryUserRoute() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_QueryUserRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUserRoute(::grpc::ServerContext* /*context*/, const ::status::RouteReq* /*request*/, ::status::RouteResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryUserRoute(::grpc::ServerContext* context, ::status::RouteReq* request, ::grpc::ServerAsyncResponseWriter< ::status::RouteResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_KickUser() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::status::KickUserReq* /*request*/, ::status::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestKickUser(::grpc::ServerContext* context, ::status::KickUserReq* request, ::grpc::ServerAsyncResponseWriter< ::status::KickUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetNodes() {
      ::grpc::Service::MarkMethodAsync(8);
    }
    ~WithAsyncMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::status::GetNodesReq* /*request*/, ::status::GetNodesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNodes(::grpc::ServerContext* context, ::status::GetNodesReq* request, ::grpc::ServerAsyncResponseWriter< ::status::GetNodesResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterNode<WithAsyncMethod_DeregisterNode<WithAsyncMethod_Heartbeat<WithAsyncMethod_AllocateServer<WithAsyncMethod_ReportOnline<WithAsyncMethod_ReportOffline<WithAsyncMethod_QueryUserRoute<WithAsyncMethod_KickUser<WithAsyncMethod_GetNodes<Service > > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterNode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::status::RegisterNodeReq, ::status::RegisterNodeResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::RegisterNodeReq* request, ::status::RegisterNodeResp* response) { return this->RegisterNode(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterNode(
        ::grpc::MessageAllocator< ::status::RegisterNodeReq, ::status::RegisterNodeResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::RegisterNodeReq, ::status::RegisterNodeResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::status::RegisterNodeReq* /*request*/, ::status::RegisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterNode(
      ::grpc::CallbackServerContext* /*context*/, const ::status::RegisterNodeReq* /*request*/, ::status::RegisterNodeResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeregisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeregisterNode() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::status::DeregisterNodeReq, ::status::DeregisterNodeResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::DeregisterNodeReq* request, ::status::DeregisterNodeResp* response) { return this->DeregisterNode(context, request, response); }));}
    void SetMessageAllocatorFor_DeregisterNode(
        ::grpc::MessageAllocator< ::status::DeregisterNodeReq, ::status::DeregisterNodeResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::DeregisterNodeReq, ::status::DeregisterNodeResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeregisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeregisterNode(::grpc::ServerContext* /*context*/, const ::status::DeregisterNodeReq* /*request*/, ::status::DeregisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeregisterNode(
      ::grpc::CallbackServerContext* /*context*/, const ::status::DeregisterNodeReq* /*request*/, ::status::DeregisterNodeResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::status::HeartbeatReq, ::status::HeartbeatResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::HeartbeatReq* request, ::status::HeartbeatResp* response) { return this->Heartbeat(context, request, response); }));}
    void SetMessageAllocatorFor_Heartbeat(
        ::grpc::MessageAllocator< ::status::HeartbeatReq, ::status::HeartbeatResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::HeartbeatReq, ::status::HeartbeatResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::status::HeartbeatReq* /*request*/, ::status::HeartbeatResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::status::HeartbeatReq* /*request*/, ::status::HeartbeatResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AllocateServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AllocateServer() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::status::AllocateServerReq, ::status::AllocateServerResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::AllocateServerReq* request, ::status::AllocateServerResp* response) { return this->AllocateServer(context, request, response); }));}
    void SetMessageAllocatorFor_AllocateServer(
        ::grpc::MessageAllocator< ::status::AllocateServerReq, ::status::AllocateServerResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::AllocateServerReq, ::status::AllocateServerResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AllocateServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateServer(::grpc::ServerContext* /*context*/, const ::status::AllocateServerReq* /*request*/, ::status::AllocateServerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AllocateServer(
      ::grpc::CallbackServerContext* /*context*/, const ::status::AllocateServerReq* /*request*/, ::status::AllocateServerResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportOnline() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::status::OnlineReportReq, ::status::OnlineReportResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::OnlineReportReq* request, ::status::OnlineReportResp* response) { return this->ReportOnline(context, request, response); }));}
    void SetMessageAllocatorFor_ReportOnline(
        ::grpc::MessageAllocator< ::status::OnlineReportReq, ::status::OnlineReportResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::OnlineReportReq, ::status::OnlineReportResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOnline(::grpc::ServerContext* /*context*/, const ::status::OnlineReportReq* /*request*/, ::status::OnlineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportOnline(
      ::grpc::CallbackServerContext* /*context*/, const ::status::OnlineReportReq* /*request*/, ::status::OnlineReportResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportOffline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportOffline() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::status::OfflineReportReq, ::status::OfflineReportResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::OfflineReportReq* request, ::status::OfflineReportResp* response) { return this->ReportOffline(context, request, response); }));}
    void SetMessageAllocatorFor_ReportOffline(
        ::grpc::MessageAllocator< ::status::OfflineReportReq, ::status::OfflineReportResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::OfflineReportReq, ::status::OfflineReportResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportOffline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOffline(::grpc::ServerContext* /*context*/, const ::status::OfflineReportReq* /*request*/, ::status::OfflineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportOffline(
      ::grpc::CallbackServerContext* /*context*/, const ::status::OfflineReportReq* /*request*/, ::status::OfflineReportResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_QueryUserRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_QueryUserRoute() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::status::RouteReq, ::status::RouteResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::RouteReq* request, ::status::RouteResp* response) { return this->QueryUserRoute(context, request, response); }));}
    void SetMessageAllocatorFor_QueryUserRoute(
        ::grpc::MessageAllocator< ::status::RouteReq, ::status::RouteResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::RouteReq, ::status::RouteResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_QueryUserRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUserRoute(::grpc::ServerContext* /*context*/, const ::status::RouteReq* /*request*/, ::status::RouteResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryUserRoute(
      ::grpc::CallbackServerContext* /*context*/, const ::status::RouteReq* /*request*/, ::status::RouteResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_KickUser() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::status::KickUserReq, ::status::KickUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::KickUserReq* request, ::status::KickUserResp* response) { return this->KickUser(context, request, response); }));}
    void SetMessageAllocatorFor_KickUser(
        ::grpc::MessageAllocator< ::status::KickUserReq, ::status::KickUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::KickUserReq, ::status::KickUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::status::KickUserReq* /*request*/, ::status::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* KickUser(
      ::grpc::CallbackServerContext* /*context*/, const ::status::KickUserReq* /*request*/, ::status::KickUserResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetNodes() {
      ::grpc::Service::MarkMethodCallback(8,
          new ::grpc::internal::CallbackUnaryHandler< ::status::GetNodesReq, ::status::GetNodesResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::status::GetNodesReq* request, ::status::GetNodesResp* response) { return this->GetNodes(context, request, response); }));}
    void SetMessageAllocatorFor_GetNodes(
        ::grpc::MessageAllocator< ::status::GetNodesReq, ::status::GetNodesResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(8);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::status::GetNodesReq, ::status::GetNodesResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::status::GetNodesReq* /*request*/, ::status::GetNodesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNodes(
      ::grpc::CallbackServerContext* /*context*/, const ::status::GetNodesReq* /*request*/, ::status::GetNodesResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterNode<WithCallbackMethod_DeregisterNode<WithCallbackMethod_Heartbeat<WithCallbackMethod_AllocateServer<WithCallbackMethod_ReportOnline<WithCallbackMethod_ReportOffline<WithCallbackMethod_QueryUserRoute<WithCallbackMethod_KickUser<WithCallbackMethod_GetNodes<Service > > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterNode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::status::RegisterNodeReq* /*request*/, ::status::RegisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeregisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeregisterNode() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DeregisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeregisterNode(::grpc::ServerContext* /*context*/, const ::status::DeregisterNodeReq* /*request*/, ::status::DeregisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Heartbeat() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::status::HeartbeatReq* /*request*/, ::status::HeartbeatResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AllocateServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AllocateServer() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_AllocateServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateServer(::grpc::ServerContext* /*context*/, const ::status::AllocateServerReq* /*request*/, ::status::AllocateServerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportOnline() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_ReportOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOnline(::grpc::ServerContext* /*context*/, const ::status::OnlineReportReq* /*request*/, ::status::OnlineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportOffline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportOffline() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_ReportOffline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOffline(::grpc::ServerContext* /*context*/, const ::status::OfflineReportReq* /*request*/, ::status::OfflineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_QueryUserRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_QueryUserRoute() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_QueryUserRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUserRoute(::grpc::ServerContext* /*context*/, const ::status::RouteReq* /*request*/, ::status::RouteResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_KickUser() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::status::KickUserReq* /*request*/, ::status::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetNodes() {
      ::grpc::Service::MarkMethodGeneric(8);
    }
    ~WithGenericMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::status::GetNodesReq* /*request*/, ::status::GetNodesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterNode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::status::RegisterNodeReq* /*request*/, ::status::RegisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterNode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeregisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeregisterNode() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DeregisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeregisterNode(::grpc::ServerContext* /*context*/, const ::status::DeregisterNodeReq* /*request*/, ::status::DeregisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeregisterNode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::status::HeartbeatReq* /*request*/, ::status::HeartbeatResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AllocateServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AllocateServer() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_AllocateServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateServer(::grpc::ServerContext* /*context*/, const ::status::AllocateServerReq* /*request*/, ::status::AllocateServerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAllocateServer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportOnline() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_ReportOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOnline(::grpc::ServerContext* /*context*/, const ::status::OnlineReportReq* /*request*/, ::status::OnlineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportOnline(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportOffline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportOffline() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_ReportOffline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOffline(::grpc::ServerContext* /*context*/, const ::status::OfflineReportReq* /*request*/, ::status::OfflineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportOffline(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryUserRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_QueryUserRoute() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_QueryUserRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUserRoute(::grpc::ServerContext* /*context*/, const ::status::RouteReq* /*request*/, ::status::RouteResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryUserRoute(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_KickUser() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::status::KickUserReq* /*request*/, ::status::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestKickUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetNodes() {
      ::grpc::Service::MarkMethodRaw(8);
    }
    ~WithRawMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::status::GetNodesReq* /*request*/, ::status::GetNodesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNodes(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterNode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterNode(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::status::RegisterNodeReq* /*request*/, ::status::RegisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterNode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeregisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeregisterNode() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeregisterNode(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeregisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeregisterNode(::grpc::ServerContext* /*context*/, const ::status::DeregisterNodeReq* /*request*/, ::status::DeregisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeregisterNode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Heartbeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::status::HeartbeatReq* /*request*/, ::status::HeartbeatResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AllocateServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AllocateServer() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AllocateServer(context, request, response); }));
    }
    ~WithRawCallbackMethod_AllocateServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateServer(::grpc::ServerContext* /*context*/, const ::status::AllocateServerReq* /*request*/, ::status::AllocateServerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AllocateServer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportOnline() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportOnline(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOnline(::grpc::ServerContext* /*context*/, const ::status::OnlineReportReq* /*request*/, ::status::OnlineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportOnline(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportOffline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportOffline() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportOffline(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportOffline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportOffline(::grpc::ServerContext* /*context*/, const ::status::OfflineReportReq* /*request*/, ::status::OfflineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportOffline(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_QueryUserRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_QueryUserRoute() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->QueryUserRoute(context, request, response); }));
    }
    ~WithRawCallbackMethod_QueryUserRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUserRoute(::grpc::ServerContext* /*context*/, const ::status::RouteReq* /*request*/, ::status::RouteResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryUserRoute(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_KickUser() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->KickUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::status::KickUserReq* /*request*/, ::status::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* KickUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetNodes() {
      ::grpc::Service::MarkMethodRawCallback(8,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetNodes(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::status::GetNodesReq* /*request*/, ::status::GetNodesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNodes(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterNode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::RegisterNodeReq, ::status::RegisterNodeResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::RegisterNodeReq, ::status::RegisterNodeResp>* streamer) {
                       return this->StreamedRegisterNode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::status::RegisterNodeReq* /*request*/, ::status::RegisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterNode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::RegisterNodeReq,::status::RegisterNodeResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeregisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeregisterNode() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::DeregisterNodeReq, ::status::DeregisterNodeResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::DeregisterNodeReq, ::status::DeregisterNodeResp>* streamer) {
                       return this->StreamedDeregisterNode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeregisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeregisterNode(::grpc::ServerContext* /*context*/, const ::status::DeregisterNodeReq* /*request*/, ::status::DeregisterNodeResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeregisterNode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::DeregisterNodeReq,::status::DeregisterNodeResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Heartbeat() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::HeartbeatReq, ::status::HeartbeatResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::HeartbeatReq, ::status::HeartbeatResp>* streamer) {
                       return this->StreamedHeartbeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::status::HeartbeatReq* /*request*/, ::status::HeartbeatResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHeartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::HeartbeatReq,::status::HeartbeatResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AllocateServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AllocateServer() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::AllocateServerReq, ::status::AllocateServerResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::AllocateServerReq, ::status::AllocateServerResp>* streamer) {
                       return this->StreamedAllocateServer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AllocateServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AllocateServer(::grpc::ServerContext* /*context*/, const ::status::AllocateServerReq* /*request*/, ::status::AllocateServerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAllocateServer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::AllocateServerReq,::status::AllocateServerResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportOnline() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::OnlineReportReq, ::status::OnlineReportResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::OnlineReportReq, ::status::OnlineReportResp>* streamer) {
                       return this->StreamedReportOnline(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportOnline(::grpc::ServerContext* /*context*/, const ::status::OnlineReportReq* /*request*/, ::status::OnlineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportOnline(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::OnlineReportReq,::status::OnlineReportResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportOffline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportOffline() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::OfflineReportReq, ::status::OfflineReportResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::OfflineReportReq, ::status::OfflineReportResp>* streamer) {
                       return this->StreamedReportOffline(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportOffline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportOffline(::grpc::ServerContext* /*context*/, const ::status::OfflineReportReq* /*request*/, ::status::OfflineReportResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportOffline(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::OfflineReportReq,::status::OfflineReportResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryUserRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_QueryUserRoute() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::RouteReq, ::status::RouteResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::RouteReq, ::status::RouteResp>* streamer) {
                       return this->StreamedQueryUserRoute(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_QueryUserRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryUserRoute(::grpc::ServerContext* /*context*/, const ::status::RouteReq* /*request*/, ::status::RouteResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryUserRoute(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::RouteReq,::status::RouteResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_KickUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_KickUser() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::KickUserReq, ::status::KickUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::KickUserReq, ::status::KickUserResp>* streamer) {
                       return this->StreamedKickUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_KickUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status KickUser(::grpc::ServerContext* /*context*/, const ::status::KickUserReq* /*request*/, ::status::KickUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedKickUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::KickUserReq,::status::KickUserResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetNodes() {
      ::grpc::Service::MarkMethodStreamed(8,
        new ::grpc::internal::StreamedUnaryHandler<
          ::status::GetNodesReq, ::status::GetNodesResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::status::GetNodesReq, ::status::GetNodesResp>* streamer) {
                       return this->StreamedGetNodes(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::status::GetNodesReq* /*request*/, ::status::GetNodesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNodes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::status::GetNodesReq,::status::GetNodesResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterNode<WithStreamedUnaryMethod_DeregisterNode<WithStreamedUnaryMethod_Heartbeat<WithStreamedUnaryMethod_AllocateServer<WithStreamedUnaryMethod_ReportOnline<WithStreamedUnaryMethod_ReportOffline<WithStreamedUnaryMethod_QueryUserRoute<WithStreamedUnaryMethod_KickUser<WithStreamedUnaryMethod_GetNodes<Service > > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterNode<WithStreamedUnaryMethod_DeregisterNode<WithStreamedUnaryMethod_Heartbeat<WithStreamedUnaryMethod_AllocateServer<WithStreamedUnaryMethod_ReportOnline<WithStreamedUnaryMethod_ReportOffline<WithStreamedUnaryMethod_QueryUserRoute<WithStreamedUnaryMethod_KickUser<WithStreamedUnaryMethod_GetNodes<Service > > > > > > > > > StreamedService;
};

}  // namespace status


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_status_2eproto__INCLUDED
